# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# env:
#   GKE_PROJECT: "regal-sled-296213"
#   GKE_EMAIL: ${{ secrets.GKE_EMAIL }}
#   GITHUB_SHA: ${{ github.sha }}
#   GKE_ZONE: europe-west2-c
#   GKE_CLUSTER: cluster-2
#   DEPLOYMENT_NAME: web-page-go


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check value 
        run: ./check-value.sh
        shell: bash
